# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_expense_analiz_wnd(object):
    def setupUi(self, expense_analiz_wnd):
        expense_analiz_wnd.setObjectName("expense_analiz_wnd")
        expense_analiz_wnd.resize(710, 510)
        expense_analiz_wnd.setStyleSheet("background-color: rgb(255, 255,240);")
        self.centralwidget = QtWidgets.QWidget(expense_analiz_wnd)
        self.centralwidget.setObjectName("centralwidget")
        self.back_btn_exp = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn_exp.setGeometry(QtCore.QRect(645, 10, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(14)
        self.back_btn_exp.setFont(font)
        self.back_btn_exp.setObjectName("back_btn_exp")
        self.label_expense = QtWidgets.QLabel(self.centralwidget)
        self.label_expense.setGeometry(QtCore.QRect(20, 60, 640, 480))
        self.label_expense.setText("")
        self.label_expense.setObjectName("label_expense")
        expense_analiz_wnd.setCentralWidget(self.centralwidget)

        self.retranslateUi(expense_analiz_wnd)
        QtCore.QMetaObject.connectSlotsByName(expense_analiz_wnd)

    def retranslateUi(self, expense_analiz_wnd):
        _translate = QtCore.QCoreApplication.translate
        expense_analiz_wnd.setWindowTitle(_translate("expense_analiz_wnd", "Анализ расходов"))
        self.back_btn_exp.setText(_translate("expense_analiz_wnd", "<-"))
